### PR TITLE
Add transaction info to tour.md

### PR DESCRIPTION
**Pull request by joekarl**

### CODE REVIEW

**Comment by jklukas** [comment]
+1, although we should understand the Travis failure:
```
[ERROR] Failed to execute goal on project jdub_2.11: Could not resolve dependencies for project com.simple:jdub_2.11:jar:0.9.0: Could not find artifact com.simple:simplespec_2.11:jar:0.8.4 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by joekarl** [comment]
Yeah, the travis failure is because simplespec hasn't been pushed to maven central yet, I think @parsnips knows how to do that...

**Comment by parsnips** [comment]
Just saw this.. Will start pushing up new builds this evening.

**Comment by jklukas** [comment]
I move that we merge this now, even though CI is failing. It only touches docs.

**Comment by swenson** [comment]
+1

**Comment by parsnips** [comment]
merged.  new artifacts are out for jdub and simplespec too.

**Pull request merged**
