### PR TITLE
trim function should handle queries with comments

### PR DESCRIPTION
**Pull request by jklukas**
Currently, if `trim` is called on a multiline string containing SQL comments, the result is invalid SQL. This PR modifies the `trim` function to preserve the break after any line that looks like it might contain a comment. It should produce identical output for uncommented queries.

The entirely correct solution here would be to strip all comments, but that greatly increases complexity to the point that we would probably want use a SQL parsing library. That seems ridiculous.

The minimal alternative would be to leave the `trim` function as is, but add comments and documentation which draw attention to the lack of commenting support.

### CODE REVIEW

**Comment by parsnips** [comment]
I dont know how I feel about this PR.  It seems to me that comments should be in the scala/java code and not risk further parsing problems due to errors created by `trim`

-1

**Comment by joekarl** [comment]
While I think I agree in premise that this would be nice, there's some tricky bits here.
It looks like this just checks for `--` which indicates the start of a comment, but those characters can also occur inside of a string which wouldn't start a comment (ie `select * from x where str = 'blah -- blah'`).
The code change here would wreck that where clause. 

I think I'm with @parsnips here, easier to say we don't support "rest of the line" comments in sql than start building a sql parsing library.

-1

**Comment by jklukas** [comment]
I think I'm -1 at this point too.

Still think the docs on trim should make it clear that `--`-style comments aren't supported.

**Comment by parsnips** [comment]
+1 on docs indicating @jklukas

**Comment by jklukas** [comment]
Closing in favor of https://github.com/SimpleFinance/jdub/pull/46.

**Pull request closed without merging**
